# Jupyter Book Configuration File
# https://jupyterbook.org/en/stable/customize/config.html

title: "Local and Controllable LLMs"
author: "tollef jørgensen"
# logo: "path/to/logo.png" # Optional: Path to a logo
logo: "assets/lcllm-logo.png"
favicon: "assets/favicon.ico" # Optional: Path to a favicon
language: "en"

repository:
  url: "https://github.com/tollefj/controllable-local-LLM/"
html:
  use_repository_button: true

root: 01-landing
chapters:
  - file: 02-setup
  - file: 03-api
  - file: 04-models

# launch_buttons:
#   notebook_interface: "jupyterlab" # Interface for launching notebooks
# colab_url: "https://colab.research.google.com/"
# binderhub_url: "https://mybinder.org/" # Replace with your BinderHub if customized

exclude_patterns:
  - "**/.ipynb_checkpoints"
  - "**/.DS_Store"
  - "**/src"

execute:
  execute_notebooks: "cache" # Options: auto, force, cache
  timeout: 120 # Execution timeout for notebooks in seconds

# theme:
#   options:
#     repository_branch: "main"
#     path_to_docs: "docs/"
#     launch_buttons: true
#     use_fullscreen_button: true

# bibtex_bibfiles:
#   - references.bib # BibTeX file for citations

# plugins:
#   myst_nb:
#     enable_eval_rst: true
#   jupyterlite: # Enable JupyterLite for interactive notebook previews
#     server_extensions:
#       - jupyterlite-xeus-python

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default! See here: https://jupyterbook.org/en/stable/customize/config.html
    - html_image
